In [1]:
import spacy
nlp = spacy.load('en_core_web_lg')

c:\Users\benha\anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\Users\benha\anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\Users\benha\anaconda3\envs\py36\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\Users\benha\anaconda3\envs\py36\lib\site-packages\tensorflow\python\frame

In [2]:
nlp('king').vector

array([-1.1296e-01, -4.1865e+00, -1.8453e+00,  3.0781e-01,  2.4956e+00,
        9.6267e-01, -1.8161e+00,  4.4655e+00, -2.8210e+00,  9.7090e-01,
        1.3542e+01,  4.3195e-01, -5.3098e+00,  4.7098e+00,  2.9030e+00,
        1.5588e+00,  6.0064e+00, -3.0345e+00,  1.0626e+00, -7.7197e-01,
       -5.4771e+00, -9.7380e-01, -4.4345e+00,  5.8367e+00,  2.4302e+00,
       -3.9408e+00, -9.1862e-01, -4.9124e+00,  1.4591e+00, -7.2772e-01,
        3.4957e+00, -4.0077e+00, -1.8354e+00, -4.1052e+00,  4.9211e+00,
       -9.7053e-01,  1.9223e+00,  5.2605e+00,  1.6086e+00,  7.1328e-01,
       -1.2146e+00, -1.9869e+00,  8.0265e-01,  2.9298e+00,  7.2985e-01,
       -6.2892e-01, -1.7082e+00,  1.9893e+00,  4.7529e-01,  3.2264e+00,
       -3.9215e+00,  4.6556e+00,  1.3475e+00, -1.0979e+00, -3.0365e+00,
        1.5815e+00,  2.2835e+00, -4.0616e+00,  2.5730e+00,  4.0618e+00,
        9.5438e-01, -6.2563e+00,  5.6463e+00, -3.8933e+00,  4.4076e+00,
        2.0517e+00, -6.6906e+00, -6.9448e+00,  6.0371e+00,  9.30

In [5]:
res = nlp('king').vector - nlp('man').vector + nlp('woman').vector
res

array([ 1.9392200e+00, -2.3115001e+00, -1.3863000e+00, -1.9133999e+00,
        4.1749401e+00, -1.5401300e+00, -3.8272700e+00,  5.0291996e+00,
       -2.4454002e+00,  2.0851002e+00,  1.6605499e+01, -1.3788500e+00,
       -5.7085404e+00,  2.7210798e+00,  6.6530025e-01,  3.4804001e+00,
        1.0497000e+00, -1.1281996e+00, -6.6435003e-01, -3.5216696e+00,
       -8.0680294e+00, -3.8434997e+00, -4.4948001e+00,  8.7943001e+00,
       -6.3383985e-01, -4.8098001e+00, -1.2955203e+00, -6.1078286e-01,
        4.1610003e-01, -4.1724200e+00,  3.7961500e+00, -5.5350199e+00,
       -1.4319000e+00, -4.7633996e+00,  3.7440000e+00, -1.2749730e+00,
        3.1816001e+00,  1.0476298e+00,  1.0784001e+00, -3.0779200e+00,
       -1.2711000e+00, -3.6251001e+00, -2.7258501e+00,  4.7676001e+00,
        1.5000498e+00,  2.5363998e+00,  9.6959996e-01,  2.8748999e+00,
        2.6771998e+00,  1.8741999e+00, -5.3535199e+00,  3.7624002e+00,
       -5.4443008e-01, -2.8594000e+00, -2.3983500e+00,  7.5615001e-01,
      

In [15]:
nlp('man').similarity(nlp('human'))

0.2533094463340689

In [16]:
nlp('I like school').similarity(nlp('I hate school'))

0.9502732184322309

In [17]:
nlp('lovely').similarity(nlp('sunshine'))

0.4966852991960575

In [18]:
nlp('film').similarity(nlp('movie'))

0.8332769376188796

In [28]:
arr = (nlp('man').vector == nlp.vocab['man'].vector)
list(arr).count(False)

0

## Generating similar words

In [3]:
import numpy as np

your_word = "king"

ms = nlp.vocab.vectors.most_similar(
    np.asarray([nlp.vocab.vectors[nlp.vocab.strings[your_word]]]), n=10)
words = [nlp.vocab.strings[w] for w in ms[0][0]]
distances = ms[2]
print(words)

['king', 'kings', 'kingi', 'princes', 'princeling', 'kingii', 'prince', 'ruler', 'princelings', 'kingship']


In [ ]:
puppy = nlp('dog').vector - nlp('man').vector + nlp('baby').vector

In [9]:
ms = nlp.vocab.vectors.most_similar(
    np.asarray([puppy]), n=10)
words = [nlp.vocab.strings[w] for w in ms[0][0]]
distances = ms[2]
print(words)

['pet', 'dog', 'puppy', 'furbaby', 'uppy', 'pup', 'cat', 'baby', 'kitt', 'Hushpuppy']


In [10]:
ms = nlp.vocab.vectors.most_similar(
    np.asarray([nlp('puppy').vector]), n=10)
words = [nlp.vocab.strings[w] for w in ms[0][0]]
distances = ms[2]
print(words)

['puppy', 'uppy', 'Hushpuppy', 'puppies', 'guppy', 'pup', 'duppy', 'yuppy', 'dog', 'Duppy']


In [45]:
ms

(array([[10467886468764181784,  2546273072073312032, 12964175481962059394,
         13192779106523156987,  8012374306420433898,   725209919693816075,
         17429802345416193488,  2355605237545211909,  7562983679033046312,
          1139192909177073838]], dtype=uint64),
 array([[  9003, 303706, 327975,  11580, 153913,  21114, 510601, 419548,
           1147, 255116]], dtype=int32),
 array([[1.    , 0.876 , 0.8569, 0.8512, 0.8324, 0.8308, 0.8223, 0.8148,
         0.8108, 0.7945]], dtype=float32))

## Getting similar words from specific set of words

In [32]:
def vec(word: str) -> np.ndarray:
    return nlp(word).vector

In [56]:
from scipy import spatial

man = vec(word='man')
woman = vec('woman')
king = vec('king')

new_vec = king - man + woman

sims = []
words = ['prince', 'George', 'hat', 'queen', 'mat', 'dog', 'space', 'drought', 'tree', 'jack']

for word in words:
    similarity = 1 - spatial.distance.cosine(new_vec, vec(word))
    sims.append((word, similarity))

sims = sorted(sims, key = lambda item: -item[1])

for a,b in sims:
    print(f'{a:{10}} {b}')


prince     0.6562830209732056
queen      0.6178014278411865
drought    0.2768979072570801
space      0.20415686070919037
tree       0.1332104355096817
George     0.09574861824512482
mat        0.03787178173661232
dog        0.03319096937775612
jack       -0.04726371914148331
hat        -0.09517838060855865


In [52]:
ms = nlp.vocab.vectors.most_similar(np.asarray([new_vec]), n = 5)
words = [nlp.vocab.strings[word_vec] for word_vec in ms[0][0]]

for word in words:
    print(word)

king
kings
princes
consort
princeling
